# 1. 수치미분 코딩

##### 1-1 입력변수가 1개

In [4]:
def numerical_dervative_1(f, x): #f는 미분하려는 함수, x는 미분 값을 알고자 하는 입력값
    delta_x = 1e-4 #lim에 해당되는 작은 값
    return (f(x+delta_x) - f(x-delta_x)) / (2*delta_x)

##### 1-2 다변수 함수

In [2]:
import numpy as np

In [14]:
def numerical_derivative_2(f, x): #f는 다변수 함수, x는 모든 변수를 포함하는 배열/객체
    delta_x = 1e-4
    grad = np.zeros_like(x) #계산된 수치미분 값 저장 변수, 현재 0으로 초기화
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    #모든 입력변수에 대해 편미분하기 위해 iterator 획득
    while not it.finished: #변수의 개수 만큼 반복
        idx = it.multi_index
        
        tmp_val = x[idx] # 원본값 보관을 위해 임시 변수 선언
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x)
        
        x[idx] = tmp_val - delta_x
        fx2 = f(x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        x[idx] = tmp_val #원본값 복원
        it.iternext()
        print(grad)

##### 1-3 예제

In [15]:
#변수가 2개일 때
def func1(input_obj):
    x = input_obj[0]
    y = input_obj[1]
    return (2*x + 3*x*y + np.power(y,3))

input = np.array([1.0, 2.0])
numerical_derivative_2(func1, input)

[8. 0.]
[ 8.         15.00000001]


In [17]:
#변수가 4개일 때
def func2(input_obj):
    w = input_obj[0,0]
    x = input_obj[0,1]
    y = input_obj[1,0]
    z = input_obj[1,1]
    
    return (w*x + x*y*z + 3*w + z*np.power(y,2))

input = np.array([[1.0, 2.0], [3.0, 4.0]])

numerical_derivative_2(func2, input)

[[5. 0.]
 [0. 0.]]
[[ 5. 13.]
 [ 0.  0.]]
[[ 5. 13.]
 [32.  0.]]
[[ 5. 13.]
 [32. 15.]]
